version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: walletTest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:1234@db:5432/
      TEST_DATABASE_URL: postgresql+asyncpg://postgres:1234@db:5432/walletTest
      HOST: 0.0.0.0
      PORT: 8000
    ports:
      - "8000:8000"
    command: ["/start.sh"]
    volumes:
      - ./:/app

volumes:
  pgdata:

